name: CI
on: [push, pull_request]

jobs:
  tests:
    name: Unit test and lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm ci
      - name: Run unit tests
        env:
          GITHUB_TOKEN: "${{ secrets.ACCESS_TOKEN_FOR_TEST }}"
          GITHUB_ACTION_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        run: npm test
      - run: npm run lint
      - name: Check workflow files
        run: |
          echo "::add-matcher::.github/actionlint-matcher.json"
          bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
          ./actionlint -color
        shell: bash
